appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TqIkkMvUX1V/DvHKWX8TeDt3JR7DTxLVMeupTjZhzWJEe3gLkTU+gjZkQPey+jxzT95fP/B9kBCIxBA1d5RSNjujZrDdfaIJUQBKLILXZQt7NaOerTuBXcfqLwlDnx/TgpeO4J08sBoDfs1VMFQvAj0O0ehKeTCl6dxM2mDQyyjE8WDhts97E72xFdnzUXSssFbV2aqSrePEcJDjAioTMygzt9h85C9VSnwSHd3SrGIZWfRDgwvW+uNsJgAbZfECgxrAsvwDMgCQnlHJS5J3OCbN+D8sxARbw3w52MKXJ3k/S2I+el/wk3efwGw76Z5FdvR0/axNRq9mn5sH+1HDT+yry3DM1KJulvBCgDu0S7HgD+flHZRSLZZ7+Z4xfEUtuhsW8gM904SuZhCP+bWJ6z5+wX58r9Uyl3Ok5XSrZsVoQ7SwSXiM1LluXEqN5zsU5pvWaaDvBkmfHIQEzl3MsdVbJWhqv466J7OV/VY9Po56dnwEqeTC7r6hgFJYufGzxsfiAUJpiWymBlBurxYRV75K44M3aVYUTZaSQl74DDrDh7mJCcQWbSd89wqT5AsNwLQykwL1laSGEaJhB3Ucmsw6bmU5lB1nJuZH5X9N2dROXVr/q6JH06yKNOx7J+RD+U8Bmur4wAOEelE2dE8hnecwu3FatmZpUxW3uC3UaPw=}
